### ISSUE TITLE
Navbar pkgdown configuration

### ISSUE THREAD

**Issue by maelle** [igraph/rigraph#651]
Related to #650 @iosonofabio  (and needs #638 first, that adds the pkgdown infrastructure)

to get

![image](https://user-images.githubusercontent.com/8360597/215067625-052f13ca-2207-40e4-9ad7-8030360fc4a4.png)

One needs in the pkgdown config

```yaml
navbar:
  structure:
    left:
    - intro
    - reference
    - articles
    - tutorials
    - news
    right: github
  components:
    intro:
      text: Get started
      menu:
      - text: Intro in English
        href: articles/igraph.html
      - text: Intro en Español
        href: articles/igraph_ES.html
```
        
At the moment the articles menu will list the same articles, but that might change if further articles are added.
